### ISSUE TITLE
Difficulty Configuring systemd Update Schedule

### ISSUE THREAD

**Issue by AndyMandy112** [jacklul/pihole-updatelists#95]
Hi there I understand this isn't exactly an issue with the script itself, but can I please have some assistance configuring systemd to run the list update schedule.
The systemd schedule used to generate fine upon script install when running Raspbian, however I have recently changed to DietPi and that's when the difficulty started. Now on script install it mentions using crontab entry as systemd not found (I'd prefer systemd over crontab) - can I please have some help installing systemd to properly configure the update schedule.

Here is my output of "systemctl list-timers"
```
Sat 2021-11-13 09:39:00 AWST 21min left     Sat 2021-11-13 09:09:36 AWST 7min ago phpsessionclean.timer        phpsessionclean.service
Sat 2021-11-13 19:28:58 AWST 10h left       Fri 2021-11-12 19:28:58 AWST 13h ago  systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service
Mon 2021-11-15 00:59:13 AWST 1 day 15h left Fri 2021-11-12 18:28:20 AWST 14h ago  fstrim.timer                 fstrim.service

3 timers listed.
Pass --all to see loaded but inactive timers, too.
```

Thanks.

**Comment by jacklul** [comment]
Are you sure `systemd` process is running? Install script check if it's running to decide whenever install the service or crontab.
If you're sure your distro is using systemd you could import `service` and `timer` files to `/etc/systemd/system` and remove `/etc/cron.d/pihole-updatelists`, like so:

```bash
cp -v pihole-updatelists.service /etc/systemd/system
cp -v pihole-updatelists.timer /etc/systemd/system
rm /etc/cron.d/pihole-updatelists
```

I can't really help you install systemd into your distro because it's out of my league, I think that's something your distro should come installed with by default and if it's not I would suggest contacting developers for help.

**Comment by AndyMandy112** [comment]
Thanks very much :)
